### ISSUE TITLE
エディタの文字コードをUTF-8にする．

### ISSUE THREAD

**Issue by MaxMEllon** [git-study-SLP/git-recture#2]
vimの文字コードをUTF-8にして文字化けしないようにしよう．

**Comment by kattsun17** [comment]
解決しました。

**Comment by MaxMEllon** [comment]
どのようにして解決したかを書くとなおいいと思います．
変更点が多い場合は，hogehogeのXX行目~XX行目を参照とかでもいいので．

今回の場合だと，

``` vim
set encoding=utf-8
```

みたいなかんじですね

**Comment by MaxMEllon** [comment]
まだ，コミットメッセージが文字化けしているので，下のサイトを参考に不要なsetの削除 もしくは足りない設定の追加を試してみてください

[http://qiita.com/takasianpride/items/0d68fcbbcc3aaf22cf9a](http://qiita.com/takasianpride/items/0d68fcbbcc3aaf22cf9a)

**Comment by MaxMEllon** [comment]
食堂で私と直接やったのでクローズ
